'''3293'''
txt1 = input().rstrip()
txt2 = input().rstrip()
txt3 = input().rstrip()
txt4 = input().rstrip()
txt5 = input().rstrip()
lentxt = max(len(txt1),len(txt2),len(txt3),len(txt4),len(txt5))
txt1 = txt1+(' '*(lentxt-len(txt1)))
txt2 = txt2+(' '*(lentxt-len(txt2)))
txt3 = txt3+(' '*(lentxt-len(txt3)))
txt4 = txt4+(' '*(lentxt-len(txt4)))
txt5 = txt5+(' '*(lentxt-len(txt5)))
print('*'*(lentxt+4))
print(f'* {txt1} *')
print(f'* {txt2} *')
print(f'* {txt3} *')
print(f'* {txt4} *')
print(f'* {txt5} *')
print('*'*(lentxt+4))
